name: Build Python to EXE

on:
  push:
    branches: [ "main" ] # Đổi thành "master" nếu nhánh chính của bạn tên là master
  workflow_dispatch: # Cho phép bấm nút tự chạy build thủ công

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --noconsole GIMI_Mod_Folder_Manager/MFM.py

    - name: Upload Finished EXE
      uses: actions/upload-artifact@v4
      with:
        name: MFM-windows-application
        path: dist/*.exe
